@startuml
title "java network programing"
actor user
box "server" #LightBlue
database DB
end box
activate DB
DB -> user : 1. prepare socket
activate user
user -> DB : 2. connect to the socket
user -> DB : 3. throw query
note right : the query use SQL format
DB --> user : 4. return corresponded data
@enduml
